# Generated by Django 5.2.11 on 2026-02-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
