# Generated by Django 5.2.7 on 2026-02-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0009_customer_confirm_password_customer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
    ]
